AllCops:
  Exclude:
    - app/channels
    - bin/**/*
    - db/**/*
    - lib/tasks/cucumber.rake
    - features/support/env.rb
    - vendor/bundle/**/*
    - tmp/**/*
    - node_modules/**/*
    - storage/**/*
Metrics/LineLength:
  Max: 160
Style/BlockComments:
  Description: 'Do not use block comments.'
  Enabled: false
Metrics/MethodLength:
  Exclude:
Metrics/AbcSize:
  Exclude:
Style/FrozenStringLiteralComment:
  Enabled: false
