version: "3"

# Volume definitions
volumes:
  assets:
    external: false
  configs:
    external: false
  db-data:
    external: false

# Service definitions
services:
  # Webserver proxy
  webserver:
    image: "nginx:1.11.8"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - assets:/usr/share/nginx/html
      - configs:/etc/nginx/conf.d

  # Production database
  prod_db:
    image: mdillon/postgis:9.5
    env_file: .env.prod
    volumes:
      - db-data:/var/lib/postgresql/db-data

  # Production application server
  prod_web:
    build: .
    env_file: .env.prod
    ports:
      - "3000:3000"
    volumes:
      - assets:/usr/share/nginx/html
      - configs:/etc/nginx/conf.d
    depends_on:
      - prod_db
      - webserver
