# Docker compose version
version: '3'
# Service definitions
services:
  database:
    image: mdillon/postgis:9.5
    env_file: .env.dev
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  app_server:
    tty: true
    stdin_open: true
    build: .
    env_file: .env.dev
    volumes:
      - .:/plymouth-parks
      - /plymouth-parks/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - database

  # webpacker:
  #   build: .
  #   env_file:
  #     - '.env.dev'
  #   command: bash -c "rm -rf /public/packs; ./bin/webpack-dev-server"
  #   volumes:
  #     - .:/plymouth-parks
  #   ports:
  #     - '3035:3035'
  #   depends_on:
  #     - app_server
