# Docker compose version
version: '3'
# Service definitions
services:
  # Development database definition
  db:
    image: mdillon/postgis:9.5
    env_file: .env.dev
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  # Development application server definition
  web:
    build: .
    env_file: .env.dev
    volumes:
      - .:/plymouth-parks
    ports:
      - "3000:3000"
    depends_on:
      - db
