version: 2
jobs:
  bundle_install:
    docker:
      - image: circleci/ruby:2.4.5
    steps:
      - checkout
      - restore_cache:
          key: plymouths-parks-bundle-v3-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: plymouths-parks-bundle-v3-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  precompile_assets:
    docker:
      - image: circleci/ruby:2.4.5
    steps:
      - checkout
      - restore_cache:
          key: plymouths-parks-bundle-v3-{{ checksum "Gemfile.lock" }}
        - run:
          name: Install any missing gems / dependencies / extensions
          command: bundle install --path vendor/bundle
        - run:
          name: Precompile assets
          command: ./bin/rails assets:precompile
      - save_cache:
          name: Cache precompiled assets
          key: precompiled-assets-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - public/assets

  rails_tests: &rails_tests
    docker:
      - image: circleci/ruby:2.4.5-node-browsers
        environment:
          PGUSER: postgres
          RAILS_ENV: test
          PGHOST: 127.0.0.1
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: plymouth_parks_test
          POSTGRES_PASSWORD: postgres
      steps:
      - checkout
      - restore_cache:
          name: Restore bundled gems from cache
          key: plymouth-parks-bundle-v3-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          name: Restore precompiled assets from cache
          key: precompiled-assets-v1-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Install any missing gems / dependencies / extensions
          command: bundle install --path vendor/bundle
      - run:
          name: Install PG
          command: sudo apt-get update -qq && sudo apt-get install postgresql
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rails db:create
      - run: bundle exec rails db:gis:setup
      - run: bundle exec rails db:migrate
      - run:
          name: Run Tests
          command: bin/rails test test/controllers test/jobs test/lib test/mailers test/models test/policies test/texters --verbose
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test_results

  rubocop:
    docker:
      - image: circleci/ruby:2.4.5
    steps:
      - checkout
      - run:
          name: Install Rubocop
          command: sudo gem install rubocop:0.47.1
      - run: rubocop

workflows:
  version: 2
  run_tests:
    jobs:
      - bundle_install:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
      - rubocop
      - precompile_assets:
          requires:
            - bundle_install
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
      - rails_tests:
          requires:
            - bundle_install
            - precompile_assets
