#!/bin/bash -e

echo "Starting compose..."

if [[ -a /tmp/puma.pid ]]; then
  rm /tmp/puma.pid
fi

if [[ $RAILS_ENV == "production" ]]; then
  # Precompile assets
  rails assets:precompile
  # Migrate database
  rails db:migrate
  # Create nginx html directory
  mkdir -p /usr/share/nginx/html
  # Copy public to nginx html
  cp -R public/* /usr/share/nginx/html
  # Create nginx conf.d directory
  mkdir -p /etc/nginx/conf.d/
  # Copy
  cp site-ssl.conf /etc/nginx/conf.d/default.conf
  # nginx ssl config
  cp config/certbot/conf/options-ssl-nginx.conf /etc/letsencrypt/options-ssl-nginx.conf
  # Copy over ssl-dhparams pem file
  cp config/certbot/conf/ssl-dhparams.pem /etc/letsencrypt/ssl-dhparams.pem
  # Create certbot directory
  mkdir -p /var/www/certbot
fi

rails server -b 0.0.0.0 -P /tmp/puma.pid
