#!/bin/bash -e

echo "Starting compose..."

if [[ -a /tmp/puma.pid ]]; then
  rm /tmp/puma.pid
fi

if [[ $RAILS_ENV == "production" ]]; then
  # Precompile assets
  rails assets:precompile
  # Migrate database
  rails db:migrate
  # Create nginx html directory
  mkdir -p /usr/share/nginx/html
  # Copy public to nginx html
  cp -R public/* /usr/share/nginx/html
  # Create nginx conf.d directory
  mkdir -p /etc/nginx/conf.d/
  # Copy
  cp site.conf /etc/nginx/conf.d/default.conf
fi

rails server -b 0.0.0.0 -P /tmp/puma.pid
